### ISSUE TITLE
This appears to only support direct binding, and not as subclass

### ISSUE THREAD

**Issue by apatrida** [kailan/kodeinject#3]
Not sure how this works in Kodein, but if you bind to the Concrete Class for example, and the constructor accepts the implemented Interface, your type check is `==` so will not bind.  Is there an internal call you can make to Kodein to have it do the same logic it would apply?

Basically calling its `instance<type>()`?

**Comment by kailan** [comment]
Not 100% sure what you mean here, mind giving some example code?

**Comment by kailan** [comment]
Closed, this is default functionality of Kodein.
